ThietBiDienTu/Areas/Admin/Controllers/DoanhThuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThietBiDienTu.Areas.Admin.Models;

namespace ThietBiDienTu.Areas.Admin.Controllers
{
    public class DoanhThuController : Controller
    {
        private ThietBiDienTuEntities1 db = new ThietBiDienTuEntities1();
        // GET: Admin/DoanhThu
        public ActionResult Index()
        {
            
            return View();
        }
        public ActionResult TKBaThang()
        {
            if (Session["TaiKhoanAD"] != null)
            {
                int thangHienTai = DateTime.Now.Month;
                int thangTruoc = thangHienTai - 1;
                int thangTruocTruoc = thangTruoc - 1;
                ViewBag.tHT = thangHienTai;
                ViewBag.tT = thangTruoc;
                ViewBag.tTT = thangTruocTruoc;

                var tkTHT = db.ThongKeThang(DateTime.Now.Year, thangHienTai).FirstOrDefault();
                ViewBag.tkTHienTai = (int)tkTHT.TienThang;

                var tkTT = db.ThongKeThang(DateTime.Now.Year, thangTruoc).FirstOrDefault();
                ViewBag.tkThangTruoc = (int)tkTT.TienThang;

                var tkTTT = db.ThongKeThang(DateTime.Now.Year, thangTruocTruoc).FirstOrDefault();
                decimal tienThangTruocTruoc = (decimal)tkTTT.TienThang;

                ViewBag.tkTTruocTruoc = (int)tienThangTruocTruoc;

                return View();
            }
            else
            {


                return RedirectToAction("DangNhap", "DangNhap");
            }
        }
        [HttpGet]
        public ActionResult TKTheoThang(int Thang, int Nam)
        {
            if (Session["TaiKhoanAD"] != null)
            {
                var tk = db.ThongKeHoaDonTheoThang(Thang, Nam, 3);
                return View(tk.ToList());
            }
            else
            {


                return RedirectToAction("DangNhap", "DangNhap");
            }
        }
        public ActionResult TkTheoNgay(DateTime ngay)
        {
            int Ngay = ngay.Day;
            int Thang = ngay.Month;
            int Nam = ngay.Year;
            if (Session["TaiKhoanAD"] != null)
            {
                var ctdh = db.ThongKeHoaDonTheoNgay(Ngay, Thang, Nam, 3);
                return View(ctdh.ToList());
            }
            else
            {
                return RedirectToAction("DangNhap", "DangNhap");
            }
        }
        public ActionResult TKTheoKhoan(DateTime ngaybd, DateTime ngaykt)
        {
            if (Session["TaiKhoanAD"] != null)
            {
                
                if (ngaybd > ngaykt)
                {
                    
                    ModelState.AddModelError("mkktt", "Ngày bắt đầu phải nhỏ hơn ngày kết thúc.");
                    return View();
                }

                var ctdh = db.ThongKeHDTheoKhoang(ngaybd, ngaykt, 3);
                return View(ctdh.ToList());
            }
            else
            {
                return RedirectToAction("DangNhap", "DangNhap");
            }
        }

        public ActionResult TKBanRa()
        {

            if (Session["TaiKhoanAD"] != null)
            {
                var ctdh = db.ThongKeThang(DateTime.Now.Year,DateTime.Now.Month);
                return View(ctdh.ToList());
            }
            else
            {
                return RedirectToAction("DangNhap", "DangNhap");
            }
        }
        public ActionResult TKTuanBanRa()
        {

            if (Session["TaiKhoanAD"] != null)
            {
                var ctdh = db.ThongKeTuan();
                return View(ctdh.ToList());
            }
            else
            {
                return RedirectToAction("DangNhap", "DangNhap");
            }
        }
        public ActionResult TKNamBanRa()
        {

            if (Session["TaiKhoanAD"] != null)
            {
                var ctdh = db.ThongKeNam(DateTime.Now.Year);
                return View(ctdh.ToList());
            }
            else
            {
                return RedirectToAction("DangNhap", "DangNhap");
            }
        }
    }
}

ThietBiDienTu/Areas/Admin/Views/DoanhThu/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



@Html.Action("TKBaThang")

<div class="card-body">

    <h4 class="card-title text-white">Todo</h4>


    @{
        DateTime ngay = DateTime.Now;
        var currentDate = DateTime.Now;

        var currentMonth = currentDate.Month;
        var currentYear = currentDate.Year;

    }

    @Html.ActionLink("Doanh Thu Theo Tháng", "TKTheoThang", new { Thang = currentMonth, Nam = currentYear }, new { @class = "btn btn-outline-primary btn-fw mdi mdi-calendar-multiple-check" })

    <br />
    <br />
    @Html.ActionLink("Doanh Thu Theo Ngày", "TKTheoNgay", new { ngay = DateTime.Now.ToString("MM-dd-yyyy") }, new { @class = "btn btn-outline-success btn-fw mdi mdi-calendar-today" })
    <br /><br />

    @Html.ActionLink("Doanh Thu Theo Khoảng", "TKTheoKhoan", new { ngaybd = DateTime.Now.ToString("MM-dd-yyyy"), ngaykt = DateTime.Now.ToString("MM-dd-yyyy") }, new { @class = "btn btn-outline-info btn-fw mdi mdi-calendar" })

    @Html.Action("TKTuanBanRa")
    @Html.Action("TKBanRa")
    @Html.Action("TKNamBanRa")


</div>

ThietBiDienTu/Areas/Admin/Views/DoanhThu/TKBaThang.cshtml
@{
    Layout = null;
}
<style>
    #lineChart {
        width: 100%; /* Đặt chiều rộng 100% của thẻ cha */
        max-width: 600px; /* Đặt chiều rộng tối đa */
        height: auto; /* Tự động điều chỉnh chiều cao */
    }
</style>
<canvas id="lineChart"></canvas>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    // Dữ liệu mẫu cho biểu đồ
    var data = {
        labels: ["Tháng @ViewBag.tTT", "Tháng @ViewBag.tT", "Tháng @ViewBag.tHT"],
        datasets: [{
            label: "Doanh thu ba tháng gần đây",
            borderColor: "#007BFF",
            data: [@ViewBag.tkTTruocTruoc, @ViewBag.tkThangTruoc, @ViewBag.tkTHienTai]

            

        }]
    };

    // Lấy thẻ canvas
    var ctx = document.getElementById('lineChart').getContext('2d');

    // Tạo biểu đồ đường
    var myLineChart = new Chart(ctx, {
        type: 'line',
        data: data,
        options: {
            responsive: true,
            maintainAspectRatio: false
        }
    });
</script>

ThietBiDienTu/Areas/Admin/Views/DoanhThu/TKBanRa.cshtml
@model IEnumerable<ThietBiDienTu.Areas.Admin.Models.ThongKeThang_Result>
@{
    Layout = null;
}

<table class="table">
    <tr>
        <th>Số lượng hóa đơn bán ra tháng này</th>
        <th>Tổng tiền bán được</th>
        <th>Số lượng sản phẩm bán được</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.SLHDThang</td>
            <td style="color:orangered">@String.Format("{0:0,0}", item.TienThang) đ</td>
            <td>@item.SLSP</td>

        </tr>
    }
</table>

ThietBiDienTu/Areas/Admin/Views/DoanhThu/TKNamBanRa.cshtml
@model IEnumerable<ThietBiDienTu.Areas.Admin.Models.ThongKeNam_Result>
@{
    Layout = null;
}

<table class="table">
    <tr>
        <th>Số lượng hóa đơn bán ra năm này</th>
        <th>Tổng tiền bán được</th>
        <th>Số lượng sản phẩm bán được</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.SLHDNam</td>
            <td style="color:orangered">@String.Format("{0:0,0}", item.TienNam) đ</td>
            <td>@item.SLSP</td>

        </tr>
    }
</table>

ThietBiDienTu/Areas/Admin/Views/DoanhThu/TKTheoKhoan.cshtml
@model IEnumerable<ThietBiDienTu.Areas.Admin.Models.ThongKeHDTheoKhoang_Result>
@{
    ViewBag.Title = "TKTheoKhoan";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">

    <div class="container mt-5">
        <h2>Thống kê theo khoảng ngày</h2>

        @using (Html.BeginForm("TKTheoKhoan", "DoanhThu", FormMethod.Get))
        {
            <div class="form-group">
                @Html.Label("Ngày bắt đầu:", new { @class = "col-md-3 control-label" })
                <div class="col-md-9">
                    <div class="input-group date" data-provide="datepicker">
                        @Html.TextBox("ngaybd", null, new { @class = "form-control", type = "text", data_date_format = "dd-mm-yyyy" })
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-th"></span>
                        </div>
                    </div>
                    @Html.ValidationMessage("ngaybd")
                </div>

                @Html.Label("Ngày kết thúc:", new { @class = "col-md-3 control-label" })
                <div class="col-md-9">
                    <div class="input-group date" data-provide="datepicker">
                        @Html.TextBox("ngaykt", null, new { @class = "form-control", type = "text", data_date_format = "dd-mm-yyyy" })
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-th"></span>
                        </div>
                    </div>
                    @Html.ValidationMessage("ngaykt")
                </div>
            </div>
            <div class="col-md-4" style="color:orangered">
                @Html.ValidationSummary()
            </div>
            <div class="form-group">
                <div class="col-md-offset-3 col-md-9">
                    <button type="submit" class="btn btn-primary">Thực hiện</button>
                </div>
            </div>
        }


        @if (Model != null && Model.Any())
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Mã hóa đơn</th>
                        <th>Thanh toán</th>
                        <th>Tên khách hàng</th>
                        <th>Mã giảm giá</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.MaDDH</td>
                            <td style="color:orangered">@String.Format("{0:0,0}", item.ThanhTien) đ</td>
                            <td>@item.TenKH</td>
                            <td>@item.MaGiamGia</td>
                            <td>
                                <a href="@Url.Action("XemChiTietDH","DonHang", new { idDDH = item.MaDDH })" class="btn btn-outline-success btn-fw btn-fw mdi mdi-eye">
                                    Xem đơn
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>Không có dữ liệu hóa đơn cho khoảng ngày đã chọn.</p>
        }

        <!-- Thêm thư viện Bootstrap và Bootstrap Datepicker -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">

        <!-- Thêm thư viện jQuery và Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <!-- Thêm thư viện Bootstrap Datepicker JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

        <!-- Kích hoạt Datepicker -->
        <script>
            $(document).ready(function () {
                $('.date').datepicker({
                    format: 'yyyy-mm-dd',
                    autoclose: true
                });
            });
        </script>

        </div>
</div>

ThietBiDienTu/Areas/Admin/Views/DoanhThu/TKTheoThang.cshtml
@model IEnumerable<ThietBiDienTu.Areas.Admin.Models.ThongKeHoaDonTheoThang_Result>
@{
    ViewBag.Title = "TKTheoThang";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">

    <div class="container mt-5">
        <h2>Thống kê theo tháng</h2>

        @using (Html.BeginForm("TKTheoThang", "DoanhThu", FormMethod.Get))
        {
            <div class="form-group">
                @Html.Label("Tháng:")
                @Html.DropDownList("Thang", Enumerable.Range(1, 12).Select(x => new SelectListItem
        {
        Value = x.ToString(),
        Text = x.ToString(),
        Selected = x == ViewBag.SelectedMonth
        }), new { @class = "form-control" })

                @Html.Label("Năm:")
                @Html.DropDownList("Nam", Enumerable.Range(DateTime.Now.Year - 5, 10).Select(x => new SelectListItem
        {
        Value = x.ToString(),
        Text = x.ToString(),
        Selected = x == ViewBag.SelectedYear
        }), new { @class = "form-control" })

                <button type="submit" class="btn btn-primary">Thực hiện</button>
            </div>
        }

        @if (Model != null && Model.Any())
        {
            <table class="table">
                <tr>
                    <th>Mã hóa đơn</th>
                    <th>Thanh toán</th>
                    <th>Tên khách hàng</th>
                    <th>Mã giảm giá</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.MaDDH</td>
                        <td style="color:orangered">@String.Format("{0:0,0}", item.ThanhTien) đ</td>
                        <td>@item.TenKH</td>
                        <td>@item.MaGiamGia</td>
                    </tr>
                }
            </table>
        }
        else
        {
            <p>Không có dữ liệu thống kê cho tháng và năm đã chọn.</p>
        }
</div>
</div>

ThietBiDienTu/Areas/Admin/Views/DoanhThu/TKTuanBanRa.cshtml
@model IEnumerable<ThietBiDienTu.Areas.Admin.Models.ThongKeTuan_Result>
@{
    Layout = null;
}

<table class="table">
    <tr>
        <th>Số lượng hóa đơn bán ra tuần này</th>
        <th>Tổng tiền bán được</th>
        <th>Số lượng sản phẩm bán được</th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.SLHDTuan</td>
            <td style="color:orangered">@String.Format("{0:0,0}", item.TienTuan) đ</td>
            <td>@item.SLSP</td>

        </tr>
    }
</table>

ThietBiDienTu/Areas/Admin/Views/DoanhThu/TkTheoNgay.cshtml
@model IEnumerable<ThietBiDienTu.Areas.Admin.Models.ThongKeHoaDonTheoNgay_Result>
@{
    ViewBag.Title = "TkTheoNgay";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="content-wrapper">

    <div class="container mt-5">
        <h2>Thống kê theo ngày</h2>

        @using (Html.BeginForm("TkTheoNgay", "DoanhThu", FormMethod.Get))
        {
            <div class="form-group">
                @Html.Label("Ngày:", new { @class = "col-md-3 control-label" })
                <div class="col-md-9">
                    <div class="input-group date" data-provide="datepicker">
                        @Html.TextBox("Ngay", null, new { @class = "form-control", type = "text", data_date_format = "dd-mm-yyyy" })
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-th"></span>
                        </div>
                    </div>
                    @Html.ValidationMessage("Ngay")
                </div>
            </div>

            <!-- Thêm các trường khác của form tại đây -->

            <button type="submit" class="btn btn-primary">Thực hiện</button>
        }

        @if (Model != null && Model.Any())
        {
            <table class="table">
                <thead>
                    <tr>
                        <th>Mã hóa đơn</th>
                        <th>Thanh toán</th>
                        <th>Tên khách hàng</th>
                        <th>Mã giảm giá</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.MaDDH</td>
                            <td style="color:orangered">@String.Format("{0:0,0}", item.ThanhTien) đ</td>
                            <td>@item.TenKH</td>
                            <td>@item.MaGiamGia</td>
                            <td>
                                <a href="@Url.Action("XemChiTietDH","DonHang", new { idDDH = item.MaDDH })" class="btn btn-outline-success btn-fw btn-fw mdi mdi-eye">
                                    Xem đơn
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>Không có dữ liệu hóa đơn cho ngày đã chọn.</p>
        }

        <!-- Thêm thư viện Bootstrap và Bootstrap Datepicker -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">

        <!-- Thêm thư viện jQuery và Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <!-- Thêm thư viện Bootstrap Datepicker JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

        <!-- Kích hoạt Datepicker -->
        <script>
            $(document).ready(function () {
                $('.date').datepicker({
                    format: 'dd/mm/yyyy',
                    autoclose: true
                });
            });
        </script>

        </div>
</div>