ThietBiDienTu/Areas/Admin/Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThietBiDienTu.Areas.Admin.Models;

namespace ThietBiDienTu.Areas.Admin.Controllers
{
    public class DonHangController : Controller
    {
        private ThietBiDienTuEntities1 db = new ThietBiDienTuEntities1();
        //
        // GET: /Admin/NhanVien/
        public ActionResult QuanLyDonHang()
        {
            if (Session["TaiKhoanAD"] != null)
            {

                var ddh = db.GetOrderInfoByStatus1(1);
                return View(ddh.ToList());
            }
            else
            {


                return RedirectToAction("DangNhap", "DangNhap");
            }

        }
        public ActionResult DaGiao()
        {
            if (Session["TaiKhoanAD"] != null)
            {

                var ddh = db.GetOrderInfoByStatus1(2);
                return View(ddh.ToList());
            }
            else
            {


                return RedirectToAction("DangNhap", "DangNhap");
            }

        }
        public ActionResult XacNhanDaGiao(int id)
        {
            if (Session["TaiKhoanAD"] != null)
            {

                var dh = db.DDHs.Find(id);


                dh.TrangThai = 3;


                db.SaveChanges();
                return RedirectToAction("QuanLyDonHang");
            }
            else
            {


                return RedirectToAction("DangNhap", "DangNhap");
            }

        }
        public ActionResult XacNhanDH(int id)
        {
            if (Session["TaiKhoanAD"] != null)
            {

                var dh = db.DDHs.Find(id);


                dh.TrangThai = 2;


                db.SaveChanges();
                return RedirectToAction("QuanLyDonHang");
            }
            else
            {


                return RedirectToAction("DangNhap", "DangNhap");
            }

        }
        public ActionResult HuyDH(int MaDDH)
        {
            if (Session["TaiKhoanAD"] != null)
            {
                ViewBag.MaDDH = MaDDH;
                return View();
            }
            else
            {


                return RedirectToAction("DangNhap", "DangNhap");
            }

        }
        [HttpPost]
        public ActionResult HuyDH(int MaDDH, String LyDo)
        {

            if (Session["TaiKhoanAD"] != null)
            {

                db.CapNhatHuyDonHangByMaDDH(MaDDH, LyDo);
                return RedirectToAction("QuanLyDonHang");
            }
            else
            {


                return RedirectToAction("DangNhap", "DangNhap");
            }




        }
        public ActionResult DaHuy()
        {
            if (Session["TaiKhoanAD"] != null)
            {
                var DaHuy = db.HuyHangs.Where(x => x.MaKH == 3);
                return View(DaHuy.ToList());
            }
            else
            {
                return RedirectToAction("DangNhap", "DangNhap");
            }

        }
        public ActionResult XemChiTietDH(int idDDH)
        {
            if (Session["TaiKhoanAD"] != null)
            {

                var XemCT = db.GetOrderInfoByMaDDH(idDDH);


                return View(XemCT.ToList());
            }
            else
            {


                return RedirectToAction("DangNhap", "DangNhap");
            }



        }
    }
}

ThietBiDienTu/Areas/Admin/Views/DonHang/DaGiao.cshtml
@model IEnumerable<ThietBiDienTu.Areas.Admin.Models.GetOrderInfoByStatus1_Result>
@{
    Layout = null;
}

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Mã đơn</th>
                <th> Tên sản phẩm</th>
                <th> Khách hàng </th>

                <th> Ngày đặt </th>
                <th> Đơn vị vận chuyển </th>
                <th> Chức năng</th>
            </tr>
        </thead>
        <tbody>
            @{
                var groupedOrders = Model.GroupBy(item => item.MaDDH).ToList();
            }

            @foreach (var group in groupedOrders)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => group.Key)
                    </td>
                    <td>
                        @foreach (var item in group)
                        {
                            <img src="~/Assets/img/@Html.DisplayFor(modelItem => item.LinkHinhAnhChinh)" class="me-2" alt="image"> @Html.DisplayFor(modelItem => item.TenSP)<br />
                        }
                    </td>
                    <td> @Html.DisplayFor(modelItem => group.First().TenNguoiNhan)</td>

                    <td> @Html.DisplayFor(modelItem => group.First().NgayDat) </td>
                    <td> @Html.DisplayFor(modelItem => group.First().TenNVC)</td>
                    <td>
                        <a href="@Url.Action("XacNhanDaGiao", new { id = group.First().MaDDH})" class="btn btn-outline-dark btn-fw mdi mdi-pencil-box">
                            Xác nhận
                        </a>
                        <a href="@Url.Action("XemChiTietDH", new { idDDH = group.First().MaDDH })" class="btn btn-outline-success btn-fw btn-fw mdi mdi-eye">
                            Xem đơn
                        </a>

                    </td>
                </tr>
            }


        </tbody>
    </table>
</div>

ThietBiDienTu/Areas/Admin/Views/DonHang/DaHuy.cshtml
@model IEnumerable<ThietBiDienTu.Areas.Admin.Models.HuyHang>
@{
    Layout = null;
}

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Mã đơn</th>
                

                <th> Ngày hủy </th>
                <th> Lý do </th>
                
            </tr>
        </thead>
        <tbody>
            @{
                var groupedOrders = Model.GroupBy(item => item.MaDDH).ToList();
            }

            @foreach (var group in groupedOrders)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => group.First().MaDDH)
                    </td>
                    
                    

                    <td> @Html.DisplayFor(modelItem => group.First().NgayHuy) </td>
                    <td> @Html.DisplayFor(modelItem => group.First().LyDonHuy)</td>
                    <td>
                        <a href="@Url.Action("XemChiTietDH", new { idDDH = group.First().MaDDH })" class="btn btn-outline-success btn-fw btn-fw mdi mdi-eye">
                            Xem đơn
                        </a>
                    </td>
                    
                </tr>
            }


        </tbody>
    </table>
</div>

ThietBiDienTu/Areas/Admin/Views/DonHang/HuyDH.cshtml
@model ThietBiDienTu.Areas.Admin.Models.HuyHang
@{
    ViewBag.Title = "HuyDH";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<style>
    .cancel-order-form-container {
        max-width: 400px;
        width: 100%;
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

        .cancel-order-form-container label {
            display: block;
            margin-bottom: 5px;
        }

        .cancel-order-form-container input {
            width: calc(100% - 10px);
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        .cancel-order-form-container button {
            background-color: #ff0000;
            color: #fff;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }

            .cancel-order-form-container button:hover {
                background-color: #cc0000;
            }
</style>

<div class="content-wrapper">
    <div class="cancel-order-form-container">
        @using (Html.BeginForm("HuyDH", "DonHang", FormMethod.Post, new { @class = "cancel-order-form" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)

        <div>
            <label for="MaDDH">Mã đơn:</label>
            <input type="text" name="MaDDH" class="lock" placeholder="Mã đơn" value="@ViewBag.MaDDH">
            
        </div>

            <div>
                <label for="LyDo">Lý do:</label>
                <input type="text" name="LyDo" class="lock" placeholder="Lý do">
            </div>

            <button type="submit">Hủy hóa đơn</button>
        }
    </div>
</div>

ThietBiDienTu/Areas/Admin/Views/DonHang/QuanLyDonHang.cshtml
@model IEnumerable<ThietBiDienTu.Areas.Admin.Models.GetOrderInfoByStatus1_Result>

@{
    ViewBag.Title = "DonHang";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="content-wrapper">

    <div class="container mt-5">
        <ul class="nav nav-tabs" id="myTabs">
            <li class="nav-item">
                <a class="nav-link active" id="tab1" data-toggle="tab" href="#content1">Các đơn hàng chờ xác nhận</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="tab2" data-toggle="tab" href="#content2">Các đơn hàng đã hoàn thành      <i class="mdi mdi-new-box"></i> @ViewBag.ChoXacNhanCount</a>

            </li>
            <li class="nav-item">
                <a class="nav-link" id="tab3" data-toggle="tab" href="#content3">Đơn hàng đã hủy  </a>

            </li>


        </ul>

        <div class="tab-content mt-2">
            <div id="content1" class="tab-pane fade show active">
                <div class="card">
                    <div class="card-body">

                        <h4 class="card-title">Tình trạng đơn hàng</h4>
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Mã đơn</th>
                                        <th> Tên sản phẩm</th>
                                        <th> Khách hàng </th>

                                        <th> Ngày đặt </th>
                                        <th> Đơn vị vận chuyển </th>
                                        <th> Chức năng</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        var groupedOrders = Model.GroupBy(item => item.MaDDH).ToList();
                                    }

                                    @foreach (var group in groupedOrders)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => group.Key)
                                            </td>
                                            <td>
                                                @foreach (var item in group)
                                                {
                                                    <img src="~/Assets/img/@Html.DisplayFor(modelItem => item.LinkHinhAnhChinh)" class="me-2" alt="image"> @Html.DisplayFor(modelItem => item.TenSP)<br />
                                                }
                                            </td>
                                            <td> @Html.DisplayFor(modelItem => group.First().TenNguoiNhan)</td>

                                            <td> @Html.DisplayFor(modelItem => group.First().NgayDat) </td>
                                            <td> @Html.DisplayFor(modelItem => group.First().TenNVC)</td>
                                            <td>
                                                <a href="@Url.Action("XacNhanDH", new { id = group.First().MaDDH})" class="btn btn-outline-dark btn-fw mdi mdi-pencil-box">
                                                    Xác nhận
                                                </a>
                                                <a href="@Url.Action("XemChiTietDH", new { idDDH = group.First().MaDDH })" class="btn btn-outline-success btn-fw btn-fw mdi mdi-eye">
                                                    Xem đơn
                                                </a>
                                                <a href="@Url.Action("HuyDH", new { MaDDH = group.First().MaDDH })" class="btn btn-outline-danger btn-fw mdi mdi-delete-forever">
                                                    Hủy
                                                </a>
                                            </td>
                                        </tr>
                                    }


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div id="content2" class="tab-pane fade">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Các đơn đã hoàn thành</h4>
                        @Html.Action("DaGiao", "DonHang")
                    </div>
                </div>
            </div>
            <div id="content3" class="tab-pane fade">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Các đơn đã hủy</h4>
                        @Html.Action("DaHuy", "DonHang")
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <script>
            $(document).ready(function () {
                $("#myTabs a").click(function (e) {
                    e.preventDefault();
                    $(this).tab('show');
                });
            });
    </script>









</div>

ThietBiDienTu/Areas/Admin/Views/DonHang/XemChiTietDH.cshtml
@model IEnumerable<ThietBiDienTu.Areas.Admin.Models.GetOrderInfoByMaDDH_Result>
@{
    ViewBag.Title = "XemChiTietDH";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@{
    decimal total = 0;
    decimal tilegiam = 0;
    decimal tiengiam = 0;
    string dvvc = "";
    decimal chiphivc = 0;
    decimal tongtien = 0;
}
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
<!-- Icon fontanwesome -->
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
<link rel="stylesheet" href="~/Assets/User/css/library.css">
<!-- Owl Slider css -->
<link rel="stylesheet" href="~/Assets/User/css/owl.carousel.min.css">
<link rel="stylesheet" href="~/Assets/User/css/owl.theme.default.min.css">
<!-- Layout -->
<link rel="stylesheet" href="~/Assets/User/css/common.css">
<!-- index -->
<link rel="stylesheet" type="text/css" href="~/Assets/User/css/cart.css">
<!-- Jquery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- Owl caroucel Js-->
<script src="~/Assets/User/js/owl.carousel.min.js"></script>
<script src="~/Assets/User/js/commonscript.js"></script>
<style>
    .container {
        font-size: 20px;
    }

    .card-body {
        font-size: 14px;
    }

    .row.title, .row.item {
        padding: 5px 0;
        margin-bottom: 5px;
    }

    .main__cart-product img {
        max-width: 100%;
        height: auto;
    }

    .card {
        width: auto;
    }

    .total-amount h3, .total-amount h2 {
        font-size: 16px;
        margin-bottom: 5px;
    }
</style>
<div class="content-wrapper">
    <div class="container">
        <div class="form-group">
            @Html.ActionLink("Quay về", "QuanLyDonHang", null, new { @class = "btn btn-outline-primary btn-fw mdi mdi-backburger" })
        </div>
        <h3 class="text-center">Chi Tiết Đơn Hàng</h3>
        <div class="card">
            <div class="card-body">
                <div class="row title">
                    <div class="col-1">Mã đơn </div>
                    <div class="col-md-5">Sản phẩm</div>
                    <div class="col-2">Giá</div>
                    <div class="col-2">Số lượng</div>
                    <div class="col-2">Thành tiền</div>
                </div>

                @foreach (var item in Model)
                {
                    total = (decimal)item.ThanhTien;
                    tilegiam = (decimal)item.TiLeGiam;
                    dvvc = (string)item.TenNVC;
                    tongtien += (decimal)item.ThanhTienSP;
                    tiengiam = tongtien * tilegiam / 100;
                    chiphivc = (decimal)item.ChiPhi;

                    <div class="row item">
                        <div class="col-1">
                            @Html.DisplayFor(modelItem => item.MaDDH)
                        </div>
                        <div class="col-md-5">
                            <div class="main__cart-product">
                                <img src="~/Assets/img/@Html.DisplayFor(modelItem => item.LinkHinhAnhChinh)" alt="">
                                <div>@Html.DisplayFor(modelItem => item.TenSP)</div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div style="color:red">@String.Format("{0:0,0}", @item.GiaTien)đ</div>
                        </div>
                        <div class="col-2">
                            <div class="buttons_added">
                                @Html.DisplayFor(modelItem => item.SoLuong)
                            </div>
                        </div>
                        <div class="col-2">
                            <div style="color:red">@String.Format("{0:0,0}", item.ThanhTienSP) đ</div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <br />
        <div class="col-md-4">
            <div class="total-amount">
                <h3>Tổng tiền hàng: @String.Format("{0:0,0}", @tongtien) đ</h3>
                <h3>Mã giảm giá: -@String.Format("{0:0,0}", @tiengiam) đ</h3>
                <h3>Phí vận chuyển @dvvc: @String.Format("{0:0,0}", @chiphivc) đ</h3>
                <h2 style="color:#ff0000">Tổng tiền cần thanh toán: @String.Format("{0:0,0}", @total) ₫</h2>
            </div>
        </div>
    </div>
</div>