ThietBiDienTu/Areas/Admin/Controllers/SanPhamAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using PagedList;
using System.Web.Mvc;
using ThietBiDienTu.Areas.Admin.Models;
using System.IO;

namespace ThietBiDienTu.Areas.Admin.Controllers
{
    public class SanPhamAdminController : Controller
    {
        private ThietBiDienTuEntities1 db = new ThietBiDienTuEntities1();

        // GET: /Admin/SanPham/
        public ActionResult Index(int? page)
        {
            if (Session["TaiKhoanAD"] != null)
            {

                int pageSize = 12; // Số lượng sản phẩm muốn hiển thị trong 1 trang
                int pageNumber = page ?? 1;

                var sanpham = db.SanPhams
                    .Include(s => s.BaoHanhs)
                    .Include(s => s.DanhMuc)
                    .Include(s => s.HinhAnh)
                    .Include(s => s.HangSanXuat)
                    .OrderBy(s => s.TenSP); // Sắp xếp theo tên sản phẩm hoặc thuộc tính bạn muốn

                var pagedSanPham = sanpham.ToPagedList(pageNumber, pageSize);

                return View(pagedSanPham);

                //return View(paginatedSanPham);
                //var sanpham = db.SanPhams.Include(s => s.BaoHanhs).Include(s => s.DanhMuc).Include(s => s.HinhAnh).Include(s => s.HangSanXuat);
                //return View(sanpham.ToList());
            }
            else
            {


                return RedirectToAction("DangNhap", "DangNhap");
            }
          
        }
        public ActionResult RenderIndex()
        {
            if (Session["TaiKhoanAD"] != null)
            {

                var sanpham = db.SanPhams.Include(s => s.BaoHanhs).Include(s => s.DanhMuc).Include(s => s.HinhAnh).Include(s => s.HangSanXuat);
                return View(sanpham.ToList());
            }
            else
            {
                return RedirectToAction("DangNhap", "DangNhap");
            }
            
        }
        public ActionResult Render()
        {
            if (Session["TaiKhoanAD"] != null)
            {
                var sanpham = db.SanPhams.Include(s => s.BaoHanhs).Include(s => s.DanhMuc).Include(s => s.HinhAnh).Include(s => s.HangSanXuat);
                return View("RenderIndex", sanpham.ToList());

            }
            else
            {
                return RedirectToAction("DangNhap", "DangNhap");
            }
            
        }


        // GET: /Admin/SanPham/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["TaiKhoanAD"] != null)
            {

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                SanPham sanpham = db.SanPhams.Find(id);
                if (sanpham == null)
                {
                    return HttpNotFound();
                }
                return View(sanpham);
            }
            else
            {
                return RedirectToAction("DangNhap", "DangNhap");
            }
            
        }

        // GET: /Admin/SanPham/Create
        public ActionResult Create()
        {
            if (Session["TaiKhoanAD"] != null)
            {

                ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "MaDanhMuc", "TenDanhMuc");

                ViewBag.MaHang = new SelectList(db.HangSanXuats, "MaHang", "TenHang");


                return View();
            }
            else
            {
                return RedirectToAction("DangNhap", "DangNhap");
            }
            
        }

        // POST: /Admin/SanPham/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]

        [ValidateAntiForgeryToken]
        public ActionResult Create(SanPhamViewModels viewModel, IEnumerable<HttpPostedFileBase> filec, IEnumerable<HttpPostedFileBase> filepu1, IEnumerable<HttpPostedFileBase> filepu2, IEnumerable<HttpPostedFileBase> filepu3)
        {
            if (Session["TaiKhoanAD"] != null)
            {
                var spc = db.SanPhams.Where(x => x.TenSP == viewModel.SanPham.TenSP);
                
                if (spc.Any())
                {
                    ModelState.AddModelError("SP", "Sản phẩm đã tồn tại");
                    ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "MaDanhMuc", "TenDanhMuc", viewModel.SanPham.MaDanhMuc);
                    ViewBag.MaHang = new SelectList(db.HangSanXuats, "MaHang", "TenHang", viewModel.SanPham.MaHang);

                    return View();
                }

                ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "MaDanhMuc", "TenDanhMuc", viewModel.SanPham.MaDanhMuc);
                ViewBag.MaHang = new SelectList(db.HangSanXuats, "MaHang", "TenHang", viewModel.SanPham.MaHang);

                foreach (var file in filec)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        // Upload file lên server
                        string fileName1 = Path.GetFileName(file.FileName);

                        viewModel.HinhAnh.LinkHinhAnhChinh = fileName1;


                    }
                }
                foreach (var file in filepu1)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        // Upload file lên server
                        string fileName1 = Path.GetFileName(file.FileName);

                        viewModel.HinhAnh.LinkHinhAnhPhu1 = fileName1;


                    }
                }
                foreach (var file in filepu2)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        // Upload file lên server
                        string fileName1 = Path.GetFileName(file.FileName);

                        viewModel.HinhAnh.LinkHinhAnhPhu2 = fileName1;


                    }
                }
                foreach (var file in filepu3)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        // Upload file lên server
                        string fileName1 = Path.GetFileName(file.FileName);

                        viewModel.HinhAnh.LinkHinhAnhPhu3 = fileName1;


                    }
                }

                if (ModelState.IsValid)
                {
                    SanPham sp = new SanPham
                    {

                        TenSP = viewModel.SanPham.TenSP,
                        GiaGoc = viewModel.SanPham.GiaGoc,
                        UuDai = viewModel.SanPham.UuDai,
                        SoLuongTon = viewModel.SanPham.SoLuongTon,
                        MaDanhMuc = viewModel.SanPham.MaDanhMuc,
                        MoTa = viewModel.SanPham.MoTa,
                        ThongSoKyThuat = viewModel.SanPham.ThongSoKyThuat,
                        MaHang = viewModel.SanPham.MaHang,
                        SoLuongDaBanRa = 0,
                        ChinhSachBaoHanh = viewModel.SanPham.ChinhSachBaoHanh,
                        NgayTao = DateTime.Now,
                        ThoiGianBaoHanh = viewModel.SanPham.ThoiGianBaoHanh,
                        TrangThai=1,
                        MaHinhAnh = 1
                    };

                    db.SanPhams.Add(sp);
                    db.SaveChanges();

                    HinhAnh ha = new HinhAnh
                    {
                        LinkHinhAnhChinh = viewModel.HinhAnh.LinkHinhAnhChinh,
                        LinkHinhAnhPhu1 = viewModel.HinhAnh.LinkHinhAnhPhu1,
                        LinkHinhAnhPhu2 = viewModel.HinhAnh.LinkHinhAnhPhu2,
                        LinkHinhAnhPhu3 = viewModel.HinhAnh.LinkHinhAnhPhu3
                    };
                    db.HinhAnhs.Add(ha);
                    db.SaveChanges();

                    sp.MaHinhAnh = ha.MaHinhAnh;

                    db.SaveChanges();
                    return RedirectToAction("Index");

                }


                return View();
            }
            else
            {
                return RedirectToAction("DangNhap", "DangNhap");
            }

            
        }

        // GET: /Admin/SanPham/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (Session["TaiKhoanAD"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                SanPham sanpham = db.SanPhams.Find(id);
                if (sanpham == null)
                {
                    return HttpNotFound();
                }
                HinhAnh hinhanh = db.HinhAnhs.Find(sanpham.MaHinhAnh);
                SanPhamViewModels viewModel = new SanPhamViewModels
                {
                    SanPham = sanpham,
                    HinhAnh = hinhanh
                };
                viewModel.SanPham.MaHinhAnh = hinhanh.MaHinhAnh; // Đảm bảo gán giá trị MaHinhAnh vào trường ẩn




                ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "MaDanhMuc", "TenDanhMuc", sanpham.MaDanhMuc);
                ViewBag.MaHinhAnh = new SelectList(db.HinhAnhs, "LinkHinhAnhChinh", "LinkHinhAnhChinh", sanpham.MaHinhAnh);
                ViewBag.MaHang = new SelectList(db.HangSanXuats, "MaHang", "TenHang", sanpham.MaHang);
                ViewBag.MaHinhAnhPhu1 = new SelectList(db.HinhAnhs, "LinkHinhAnhPhu1", "LinkHinhAnhPhu1", hinhanh.LinkHinhAnhPhu1);
                ViewBag.MaHinhAnhPhu2 = new SelectList(db.HinhAnhs, "LinkHinhAnhPhu2", "LinkHinhAnhPhu2", hinhanh.LinkHinhAnhPhu2);
                ViewBag.MaHinhAnhPhu3 = new SelectList(db.HinhAnhs, "LinkHinhAnhPhu3", "LinkHinhAnhPhu3", hinhanh.LinkHinhAnhPhu3);

ThietBiDienTu/Areas/Admin/Views/SanPhamAdmin/Create.cshtml
@model ThietBiDienTu.Areas.Admin.Models.SanPhamViewModels


@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Create", "SanPhamAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-8 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Thêm mới sản phẩm</h4>
                        <form class="form-sample" method="POST" action="URL_action">
                            @Html.AntiForgeryToken()

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.SanPham.TenSP, "Tên sản phẩm", new { @class = "col-md-3 control-label" })
                                        <div class="col-md-9">
                                            @Html.EditorFor(model => model.SanPham.TenSP, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.SanPham.TenSP)
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.SanPham.GiaGoc, "Giá gốc", new { @class = "col-md-3 control-label" })
                                        <div class="col-md-9">
                                            @Html.EditorFor(model => model.SanPham.GiaGoc, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.SanPham.GiaGoc)
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.SanPham.UuDai, "Ưu đãi", new { @class = "col-md-3 control-label" })
                                        <div class="col-md-9">
                                            @Html.EditorFor(model => model.SanPham.UuDai, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.SanPham.UuDai)
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group">
                                    Loại danh mục
                                    <div class="col-md-10">
                                        @Html.DropDownListFor(model => model.SanPham.MaDanhMuc, ViewBag.MaDanhMuc as SelectList, "Chọn danh mục", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.SanPham.MaDanhMuc)
                                    </div>
                                </div>
                                <div class="form-group">
                                    nhà sản xuất
                                    <div class="col-md-10">
                                        @Html.DropDownListFor(model => model.SanPham.MaHang, ViewBag.MaHang as SelectList, "Chọn hãng", new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.SanPham.MaHang)
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.SanPham.MoTa, "Mô tả sản phẩm", new { @class = "col-md-2 control-label" })
                                        <div class="col-md-10">
                                            <textarea name="SanPham.MoTa" id="SanPham_MoTa" class="form-control"></textarea>
                                            @Html.ValidationMessageFor(model => model.SanPham.MoTa)
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.SanPham.ThongSoKyThuat, "Thông số kỹ thuật", new { @class = "col-md-2 control-label" })
                                        <div class="col-md-10">
                                            <textarea name="SanPham.ThongSoKyThuat" id="SanPham_ThongSoKyThuat" class="form-control"></textarea>
                                            @Html.ValidationMessageFor(model => model.SanPham.ThongSoKyThuat)
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">

                            </div>

                            <div class="form-group">
                                <a>Hình ảnh chính</a>
                                <input type="file" name="filec" multiple />


                            </div>
                            <div class="form-group">
                                <a>Hình ảnh phụ 1</a>
                                <input type="file" name="filepu1" multiple />

                            </div>
                            <div class="form-group">
                                <a>Hình ảnh phụ 2</a>
                                <input type="file" name="filepu2" multiple />

                            </div>
                            <div class="form-group">
                                <a>Hình ảnh phụ 3</a>
                                <input type="file" name="filepu3" multiple />


                                <div>
                                    @Html.EditorFor(model => model.HinhAnh.LinkHinhAnhChinh, new { @class = "col-md-2 control-label", @type = "hidden", Value = "chinh" })
                                    @Html.EditorFor(model => model.HinhAnh.LinkHinhAnhPhu1, new { @class = "col-md-2 control-label", @type = "hidden", Value = "phu1" })
                                    @Html.EditorFor(model => model.HinhAnh.LinkHinhAnhPhu2, new { @class = "col-md-2 control-label", @type = "hidden", Value = "phu2" })
                                    @Html.EditorFor(model => model.HinhAnh.LinkHinhAnhPhu3, new { @class = "col-md-2 control-label", @type = "hidden", Value = "phu3" })
                                </div>


                            </div>

                            <div class="row">

                                <div class="col-md-6">
                                    <div class="form-group">
                                        Chính sách bảo hành
                                        <div class="col-md-10">
                                            <select class="form-control" id="ChinhSachBaoHanh" name="SanPham.ChinhSachBaoHanh">
                                                <option value="Bảo hành nếu có lỗi từ nhà sản xuất">Bảo hành nếu có lỗi từ nhà sản xuất</option>
                                                <option value="Bảo hành linh kiện">Bảo hành linh kiện</option>
                                                <option value="Bảo hành điện tử">Bảo hành điện tử</option>
                                            </select>
                                            @Html.ValidationMessageFor(model => model.SanPham.ChinhSachBaoHanh)
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.SanPham.ThoiGianBaoHanh, "Số tháng bảo hành", new { @class = "col-md-3 control-label" })
                                        <div class="col-md-9">
                                            @Html.EditorFor(model => model.SanPham.ThoiGianBaoHanh, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.SanPham.ThoiGianBaoHanh)
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.SanPham.SoLuongTon, "Số lượng sản phẩm", new { @class = "col-md-3 control-label" })
                                        <div class="col-md-9">
                                            @Html.EditorFor(model => model.SanPham.SoLuongTon, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.SanPham.SoLuongTon)
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4" style="color:orangered">
                                @Html.ValidationSummary()
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <button type="submit" class="btn btn-outline-primary btn-fw mdi mdi-database-plus">Create</button>

                                        </div>
                                    </div>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-4 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        @Html.Action("RenderIndex", "SanPhamAdmin")

                    </div>
                </div>
            </div>
        </div>
    </div>


}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('SanPham_MoTa');
</script>
<script>
    CKEDITOR.replace('SanPham_ThongSoKyThuat');
</script>

ThietBiDienTu/Areas/Admin/Views/SanPhamAdmin/Index.cshtml
@model PagedList.IPagedList<ThietBiDienTu.Areas.Admin.Models.SanPham>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="content-wrapper">

    <p>

        @Html.ActionLink("Thêm sản phẩm", "Create", null, new { @class = "btn btn-outline-primary btn-fw mdi mdi-database-plus" })

    </p>
    <div class="container mt-5">
    @*<div class="col-lg-12 grid-margin stretch-card">*@
        <div class="card">

            <div class="card-body">
                <h4 class="card-title">Quản lý sản phẩm</h4>

                <table class="table table-striped">

                    <thead>
                        <tr>
                            <th></th>
                            <th> Tên sản phẩm </th>
                            <th> Giá tiền </th>
                            <th> Số lượng tồn kho</th>

                            <th> Danh mục </th>
                            <th> Hãng sản xuất </th>
                            <th>Trạng thái</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="py-1">
                                    <img src="~/Assets/img/@Html.DisplayFor(modelItem => item.HinhAnh.LinkHinhAnhChinh)" alt="image" />
                                </td>
                                <td> @Html.DisplayFor(modelItem => item.TenSP) </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.GiaTien)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SoLuongTon)
                                </td>


                                <td>
                                    @Html.DisplayFor(modelItem => item.DanhMuc.TenDanhMuc)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.HangSanXuat.TenHang)
                                </td>
                                
                                    @if(item.TrangThai==1)
                                    {
                                        <td style="color:royalblue">
                                            Hiển thị
                                        </td>
                                    }
                                    else
                                    {
                                        <td style="color:orangered">
                                            Ẩn
                                        </td>
                                    }
                                
                                <td>
                                    @Html.ActionLink("Sửa", "Edit", new { id = item.MaSP }, new { @class = "btn btn-outline-dark btn-fw mdi mdi-pencil-box" }) |
                                    @Html.ActionLink("Xem chi tiết", "Details", new { id = item.MaSP }, new { @class = "btn btn-outline-success btn-fw btn-fw mdi mdi-eye" })
                                    |
                                    <a href="@Url.Action("Delete", new { id = item.MaSP })" class="btn btn-outline-danger btn-fw mdi mdi-delete-forever">
                                        Xóa
                                    </a>
                                </td>



                            </tr>
                        }

                    </tbody>
                </table>
            </div>


            <div class="pagination-container">
                <ul class="pagination">
                    <li>
                        <span>Trang @(Model.PageNumber) / @Model.PageCount</span>
                    </li>
                    <li>
                        @Html.PagedListPager(Model, page => Url.Action("Index", "SanPhamAdmin", new { page }))
                    </li>
                </ul>
            </div>


        </div>
    </div>
</div>
<style>
    

    .pagination-container {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .pagination {
        display: flex;
        list-style: none;
        margin: 0;
        padding: 0;
    }

        .pagination li {
            margin: 0 5px;
        }

        .pagination a {
            display: block;
            padding: 10px 15px;
            text-decoration: none;
            color: #000000;
            background-color: #fff;
            border: 1px solid #ddd;
            border-radius: 5px;
            transition: background-color 0.3s ease;
        }

            .pagination a:hover {
                background-color: #ddd;
            }

        .pagination .active {
            background-color: #007bff;
            color: #000000;
        }
</style>

ThietBiDienTu/Areas/Admin/Views/SanPhamAdmin/RenderIndex.cshtml
@model IEnumerable<ThietBiDienTu.Areas.Admin.Models.SanPham>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>HUIT Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/Assets/Admin/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/Assets/Admin/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <!-- End layout styles -->
    <link href="~/Assets/Admin/css/style.css" rel="stylesheet" />
    <link rel="shortcut icon" href="~/Assets/Admin/Images/favicon.ico" />
</head>
<body>
    <table class="table table-hover">
        <thead>
            <tr>
                <th></th>
                <th> Các sản phẩm đã có </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="py-1">
                        <img src="~/Assets/img/@Html.DisplayFor(modelItem => item.HinhAnh.LinkHinhAnhChinh)" alt="image" />
                    </td>
                    <td> @Html.DisplayFor(modelItem => item.TenSP) </td>




                </tr>
            }

        </tbody>
    </table>

</body>
</html>