ThietBiDienTu/Controllers/DiaChiKHController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThietBiDienTu.Areas.Admin.Models;

namespace ThietBiDienTu.Controllers
{
    public class DiaChiKHController : Controller
    {
        private ThietBiDienTuEntities1 db = new ThietBiDienTuEntities1();

        // GET: /DiaChiKH/
        public ActionResult Index()
        {
            if (Session["TaiKhoan"] != null)
            {
                // Lấy giá trị từ session
                var taiKhoan = (KhachHang)Session["TaiKhoan"];

                // Sử dụng giá trị từ session trong các logic của bạn
                var diaChi = db.GetCustomerAddress(taiKhoan.MaKH);
                ViewBag.CoTK = taiKhoan.MaKH;
                return View(diaChi.ToList());
            }
            else
            {
                ViewBag.CoTK = 0;
                // Nếu session không tồn tại, có thể chuyển hướng đến trang đăng nhập hoặc thực hiện xử lý khác
                return RedirectToAction("DangNhap", "TrangChu"); // Thay "TenController" bằng tên của controller đăng nhập
            }
        }

        // GET: /DiaChiKH/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CTDiaChi ctdiachi = db.CTDiaChis.Find(id);
            if (ctdiachi == null)
            {
                return HttpNotFound();
            }
            return View(ctdiachi);
        }

        // GET: /DiaChiKH/Create
        public ActionResult Create()
        {
            ViewBag.MaDiaChi = new SelectList(db.DiaChis, "MaDiaChi", "MaDiaChi");
            return View();
        }

        // POST: /DiaChiKH/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaCTDiaChi,MaDiaChi,SoNha,TenDuong,PhuongXa,QuanHuyen,TinhThanh,MacDinh,TenNguoiNhan,SDTNguoiNhan")] CTDiaChi ctdiachi)
        {
            if (ModelState.IsValid)
            {
                db.CTDiaChis.Add(ctdiachi);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaDiaChi = new SelectList(db.DiaChis, "MaDiaChi", "MaDiaChi", ctdiachi.MaDiaChi);
            return View(ctdiachi);
        }

        // GET: /DiaChiKH/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CTDiaChi ctdiachi = db.CTDiaChis.Find(id);
            if (ctdiachi == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDiaChi = new SelectList(db.DiaChis, "MaDiaChi", "MaDiaChi", ctdiachi.MaDiaChi);
            return View(ctdiachi);
        }

        // POST: /DiaChiKH/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaCTDiaChi,MaDiaChi,SoNha,TenDuong,PhuongXa,QuanHuyen,TinhThanh,MacDinh,TenNguoiNhan,SDTNguoiNhan")] CTDiaChi ctdiachi)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ctdiachi).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaDiaChi = new SelectList(db.DiaChis, "MaDiaChi", "MaDiaChi", ctdiachi.MaDiaChi);
            return View(ctdiachi);
        }

        // GET: /DiaChiKH/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CTDiaChi ctdiachi = db.CTDiaChis.Find(id);
            if (ctdiachi == null)
            {
                return HttpNotFound();
            }
            return View(ctdiachi);
        }

        // POST: /DiaChiKH/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CTDiaChi ctdiachi = db.CTDiaChis.Find(id);
            db.CTDiaChis.Remove(ctdiachi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ThietBiDienTu/Controllers/ThongTinDDHController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ThietBiDienTu.Areas.Admin.Models;

namespace ThietBiDienTu.Controllers
{
    public class ThongTinDDHController : Controller
    {
        private ThietBiDienTuEntities1 db = new ThietBiDienTuEntities1();
        //
        // GET: /ThongTinDDH/


        public ActionResult ThongTinDDH()
        {

            // Kiểm tra xem session có tồn tại không
            if (Session["TaiKhoan"] != null)
            {
                // Lấy giá trị từ session
                var taiKhoan = (KhachHang)Session["TaiKhoan"];

                var mggList = db.GetMaGiamGiaInfoForKhachHangAndTrangThai(taiKhoan.MaKH, 0);
                ViewBag.MGGList = new SelectList(mggList, "MaGiamGia", "TenMGG","TiLeGiam");

                var dvvc = db.NhaVanChuyens.ToList();
                ViewBag.NVCList = new SelectList(dvvc, "MaNVC", "TenNVC", "ChiPhi");

                var gia=db.GioHangs.Where(x=>x.MaKH==taiKhoan.MaKH).SingleOrDefault();
                ViewBag.GiaGio = gia.TongTienGioHang;

                var diaChi = db.GetCustomerAddress(taiKhoan.MaKH);
                ViewBag.CoTK = taiKhoan.MaKH;
                return View(diaChi.ToList());
            }
            else
            {
                ViewBag.CoTK = 0;
                // Nếu session không tồn tại, có thể chuyển hướng đến trang đăng nhập hoặc thực hiện xử lý khác
                return RedirectToAction("DangNhap", "TrangChu"); // Thay "TenController" bằng tên của controller đăng nhập
            }
        }
        [HttpPost]
        public ActionResult ThongTinDDH(string lastName, string sdt, string sonha, string duong, string phuong, string quanhuyen, string tinhthanh, string desp, string mgg, int manvc)
        {
            if (Session["TaiKhoan"] != null)
            {
                var User = (KhachHang)Session["TaiKhoan"];
                string maGiamGia = Request.Form["MaGiamGia"];
                int DVVC = Convert.ToInt32(Request.Form["MaNVC"]);
                db.CreateOrderFromCart(User.MaKH, maGiamGia, DVVC, sonha, duong, quanhuyen, phuong, quanhuyen, lastName, sdt, desp);
                if (maGiamGia != "")
                {

                    var maGiamGiaKhachHang = db.MaGiamGia_KhachHang.SingleOrDefault(m => m.MaGiamGia == maGiamGia && m.MaKH == User.MaKH);



                    maGiamGiaKhachHang.TrangThai = 1;


                    db.SaveChanges();

                }

                ViewBag.CoTK = User.MaKH;
                return RedirectToAction("Index", "DDHKH");
            }
            else
            {
                ViewBag.CoTK = 0;
                // Nếu session không tồn tại, có thể chuyển hướng đến trang đăng nhập hoặc thực hiện xử lý khác
                return RedirectToAction("DangNhap", "TrangChu"); // Thay "TenController" bằng tên của controller đăng nhập
            }
        }

        //[HttpPost]
        //public ActionResult ThongTinDDH()
        //{
        //    return View();
        //}
        public ActionResult viewNVC()
        {
            var dsNVC = db.NhaVanChuyens.ToList();


            return View(dsNVC);
        }

        public ActionResult ThemMoiDiaChi()
        {


            return View();
        }
        [HttpPost]
        public ActionResult ThemMoiDiaChi(CTDiaChi dcmoi)
        {
            if (Session["TaiKhoan"] != null)
            {
                if (ModelState.IsValid)
                { 
                var User = (KhachHang)Session["TaiKhoan"];


                var rs = db.InsertCustomerAddress(User.MaKH, dcmoi.SoNha, dcmoi.TenDuong, dcmoi.PhuongXa, dcmoi.QuanHuyen, dcmoi.TinhThanh, dcmoi.MacDinh, dcmoi.TenNguoiNhan, dcmoi.SDTNguoiNhan);
                ViewBag.CoTK = User.MaKH;
                return RedirectToAction("ThongTinDDH");
            }
                else
                {
                    ModelState.AddModelError("loi", "Vui lòng nhập đầy đủ");
                    return View();
                }    
            }
            else
            {
                ViewBag.CoTK = 0;
                // Nếu session không tồn tại, có thể chuyển hướng đến trang đăng nhập hoặc thực hiện xử lý khác
                return RedirectToAction("DangNhap", "TrangChu"); // Thay "TenController" bằng tên của controller đăng nhập
            }
        }
    }
}

ThietBiDienTu/Views/ThongTinDDH/ThemMoiDiaChi.cshtml
@model ThietBiDienTu.Areas.Admin.Models.CTDiaChi

@{
    ViewBag.Title = "ThemMoiDiaChi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    @Html.ActionLink("Quay về", "Index", "DiaChiKH")
</div>
<div class="container mt-5">
    <div class="card p-3 mx-auto" style="max-width: 600px;">
        <h2 class="text-center">Thêm địa chỉ</h2>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <hr />
            @Html.ValidationSummary(true)

            <a>Nhập số nhà</a>
            <div class="form-group">

                <div class="col-md-10">

                    @Html.EditorFor(model => model.SoNha)
                    @Html.ValidationMessageFor(model => model.SoNha)
                </div>
            </div>
            <br />

            <div class="form-group">
                <a>Nhập tên đường</a>
                <div class="col-md-10">

                    @Html.EditorFor(model => model.TenDuong)
                    @Html.ValidationMessageFor(model => model.TenDuong)
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-10">
                    <a>Chọn tỉnh thành</a>
                    <select id="city" name="TinhThanh" class="form-control">
                        <option value="" selected>Chọn tỉnh thành</option>
                    </select>
                    @Html.ValidationMessageFor(model => model.TinhThanh)
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-10">
                    <a>Chọn quận huyện</a>
                    <select id="district" name="QuanHuyen" class="form-control">
                        <option value="" selected>Chọn quận huyện</option>
                    </select>
                    @Html.ValidationMessageFor(model => model.QuanHuyen)
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-10">
                    <a>Chọn phường xã</a>
                    <select id="ward" name="PhuongXa" class="form-control">
                        <option value="" selected>Chọn phường xã</option>
                    </select>
                    @Html.ValidationMessageFor(model => model.PhuongXa)
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-10">
                    <a>Địa chỉ mặc định hay không?</a>
                    <select id="macDinhDropdown" name="MacDinh" class="form-control">
                        <option value="1">Mặc định</option>
                        <option value="2">Không mặc định</option>
                    </select>
                    @Html.ValidationMessageFor(model => model.MacDinh)
                </div>
            </div>
            <br />

            <div class="form-group">
                <div class="col-md-10">
                    <a>Tên người nhận</a>
                    @Html.EditorFor(model => model.TenNguoiNhan)
                    @Html.ValidationMessageFor(model => model.TenNguoiNhan)
                </div>
            </div>
            <br/>

            <div class="form-group">
                <div class="col-md-10">
                    <a>Số điện thoại người nhận</a>
                    @Html.EditorFor(model => model.SDTNguoiNhan)
                    @Html.ValidationMessageFor(model => model.SDTNguoiNhan)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm" class="btn btn-default" style="background-color:crimson" />
                </div>
            </div>
        }

    </div>

    
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
<script>
    const host = "https://provinces.open-api.vn/api/";
    var callAPI = (api) => {
        return axios.get(api)
            .then((response) => {
                renderData(response.data, "city");
            });
    }
    callAPI('https://provinces.open-api.vn/api/?depth=1');
    var callApiDistrict = (api) => {
        return axios.get(api)
            .then((response) => {
                renderData(response.data.districts, "district");
            });
    }
    var callApiWard = (api) => {
        return axios.get(api)
            .then((response) => {
                renderData(response.data.wards, "ward");
            });
    }

    var renderData = (array, select) => {
        let row = ' <option disable value="">Chọn</option>';
        array.forEach(element => {
            row += `<option data-id="${element.code}" value="${element.name}">${element.name}</option>`
        });
        document.querySelector("#" + select).innerHTML = row
    }

    $("#city").change(() => {
        callApiDistrict(host + "p/" + $("#city").find(':selected').data('id') + "?depth=2");
        printResult();
    });
    $("#district").change(() => {
        callApiWard(host + "d/" + $("#district").find(':selected').data('id') + "?depth=2");
        printResult();
    });
    $("#ward").change(() => {
        printResult();
    })


</script>

ThietBiDienTu/Views/ThongTinDDH/ThongTinDDH.cshtml
@model IEnumerable<ThietBiDienTu.Areas.Admin.Models.GetCustomerAddress_Result>
@{
    ViewBag.Title = "ThongTinDDH";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        {
            <div class="container">
                <h1 class="mb-3"><b>Xác nhận thông tin giao hàng</b></h1><br />
                <div class="row">
                    @Html.Action("SPGioHang", "GioHang")
                    <div class="col l-4 m-12 s-12">


                        <div class="main__pay-title">Ghi chú</div>
                        <input id="desp" name="desp" type="text" class="form-control" placeholder="Ghi chú:">



                        <div class="main__pay-title">Mã giảm giá</div>
                        @Html.DropDownList("MaGiamGia", ViewBag.MGGList as SelectList,"Chọn mã giảm giá", new { @class = "form-control" })




                        <div class="main__pay-title">Chọn đơn vị vận chuyển</div>
                        
                        @Html.DropDownList("MaNVC", ViewBag.NVCList as SelectList, new { @class = "form-control" })


                    </div>

                </div>
                <div class="row">
                    <div class="col l-8 m-12 s-12">
                        <div class="main__pay-title">Thông tin người nhận</div>
                        <select id="selectAddress" style="width: 500px; height:50px;" onchange="updateAddressFields()">
                            <option>Vui lòng chọn thông tin giao hàng</option>
                            @foreach (var item in Model)
                            {


                                <option value="@Json.Encode(new { MacDinh = item.MacDinh, TenNguoiNhan = item.TenNguoiNhan, SDTNguoiNhan = item.SDTNguoiNhan, SoNha = item.SoNha, TenDuong = item.TenDuong, PhuongXa = item.PhuongXa, QuanHuyen = item.QuanHuyen, TinhThanh = item.TinhThanh })">
                                    @if (item.MacDinh == 1)
                                    {<text>[Mặc định]</text>} @item.TenNguoiNhan, @item.SDTNguoiNhan, @item.SoNha, @item.TenDuong, @item.PhuongXa, @item.QuanHuyen, @item.TinhThanh
                                </option>
                            }


                        </select>
                        @Html.ActionLink("+ Thêm mới địa chỉ", "ThemMoiDiaChi", null, null)
                        <div class="row form-group">
                            <!-- Họ đệm -->
                            <!-- Tên -->
                            <div class="col-md-6">
                                <label for="lastName" class="form-label">Tên người nhận</label>
                                <input id="lastName" name="lastName" type="text" class="form-control" placeholder="Tên" required>
                                @*<div class="invalid-feedback">Vui lòng nhập tên khách hàng</div>*@
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-md-6">

                                <input id="sdt" name="sdt" type="text" class="form-control" placeholder="Nhập số điện thoại người nhận" required>
                                @*<div class="invalid-feedback">Vui lòng nhập số điện thoại</div>*@
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label for="phuong" class="form-label">Phường, xã</label>
                            <input id="phuong" name="phuong" type="text" class="form-control" placeholder="Nhập địa chỉ phường xã" required>
                            @*<div class="invalid-feedback ">Vui lòng nhập họ đệm</div>*@
                        </div>
                        <div class="col-md-6">
                            <label for="quanhuyen" class="form-label">Quận, huyện</label>
                            <input id="quanhuyen" name="quanhuyen" type="text" class="form-control" placeholder="Nhập địa chỉ quận, huyện"required>
                            @*<div class="invalid-feedback ">Vui lòng nhập họ đệm</div>*@
                        </div>
                        <div class="col-md-6">
                            <label for="tinhthanh" class="form-label">Tỉnh, thành phố</label>
                            <input id="tinhthanh" name="tinhthanh" type="text" class="form-control" placeholder="Nhập địa chỉ tỉnh, thành phố"required>
                            @*<div class="invalid-feedback ">Vui lòng nhập họ đệm</div>*@
                        </div>

                        <div class="row form-group">
                            <!-- Country -->
                            <!-- đường -->
                            <div class="col-md-6">
                                <label for="duong" class="form-label">Tên đường</label>
                                <input id="duong" name="duong" type="text" class="form-control" placeholder="Nhập tên đường"required>
                                @*<div class="invalid-feedback ">Vui lòng nhập tên đường </div>*@
                            </div>

                            <div class="col-md-6">
                                <label for="sonha" class="form-label">Số nhà</label>
                                <input id="sonha" name="sonha" type="text" class="form-control" placeholder="Nhập số nhà"required>
                                @*<div class="invalid-feedback ">Vui lòng nhập số nhà </div>*@
                            </div>

                        </div>

                    </div>
                    <div class="col l-4 m-12 s-12">
                        <div class="main__pay">
                            <div class="main__pay-title">Tổng số lượng</div>
                            <div class="pay-info">
                                <div class="main__pay-text">
                                    Tổng phụ
                                </div>
                                <div class="main__pay-price">
                                    @String.Format("{0:0,0}",@ViewBag.GiaGio) ₫
                                </div>
                            </div>
                            

                            <div class="row form-group">
                                <div class="col-md-12 py-2">
                                    <button class="btn btn--default orange" type="submit">Thanh Toán</button>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>

        }
    }
</body>
</html>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script>
    function updateAddressFields() {
        var selectElement = document.getElementById("selectAddress");
        var selectedValue = selectElement.value;

        // Parse the JSON string into an object
        var values = JSON.parse(selectedValue);

        // Assign values to the corresponding input fields
        document.getElementById("lastName").value = values.TenNguoiNhan;
        document.getElementById("sdt").value = values.SDTNguoiNhan;
        document.getElementById("sonha").value = values.SoNha;
        document.getElementById("duong").value = values.TenDuong;
        document.getElementById("phuong").value = values.PhuongXa;
        document.getElementById("quanhuyen").value = values.QuanHuyen;
        document.getElementById("tinhthanh").value = values.TinhThanh;
    }
</script>


<script>
    

</script>
<script src="~/Assets/User/js/main.js"></script>
<script src="~/Assets/User/js/bootstrap.js"></script>
<!--Giỏ hàng-->
<link rel="stylesheet" type="text/css" href="~/Assets/User/css/cart.css">
<link rel="stylesheet" type="text/css" href="~/Assets/User/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="~/Assets/User/css/pay.css">
@*<link rel="stylesheet" type="text/css" href="~/Assets/User/css/library.css">*@

ThietBiDienTu/Views/ThongTinDDH/viewNVC.cshtml
@model IEnumerable<ThietBiDienTu.Areas.Admin.Models.NhaVanChuyen>

@{
    Layout = null;
}




<select id="selectNVC">
    <option value="">-- Chọn --</option>
    @foreach (var item in Model)
    {

        <option>@item.MaNVC - @item.TenNVC - đ @item.ChiPhi</option>
    }



</select>